language: ruby

before_script:

  - sudo apt-get update
  - sudo apt-get install -y python-software-properties

  - sudo apt-get install -y software-properties-common
  - sudo add-apt-repository -y ppa:ondrej/php5-5.6
  - sudo apt-get update
  # - sudo apt-get upgrade -y # temporarily disabled''
  - sudo apt-get install -y php5 php5-mysql php5-curl

  - sudo apt-get install -y wget
  - wget https://getcomposer.org/composer.phar
  - chmod u+x composer.phar

  - ./composer.phar install

  - ./vendor/bin/phpunit tests